### PR TITLE
When it is not a member ID that can be split by "."

### PR DESCRIPTION
**Pull request by ghost**
# How things got this way
When change bot's nickname in server, I copied bot's ID from right-click popup.  
Then I executed below code.
```php
$botId = "123456789012345678";
$name = "Steve";
$this->plugin->getDiscordBot()->getApi()->updateNickname($botId, $name);
```
That's when I got this error.
```
ErrorException: "Undefined array key 1" (EXCEPTION) in "plugins/DiscordBot.phar/src/Plugin/Api" at line 650
```

### CODE REVIEW

**Comment by ghost** [comment]
If you have one, please tell me how to get a member ID that can be split with "."

**Comment by JaxkDev** [comment]
A member ID by design will ALWAYS be in the format `serverID.userID`

**Comment by JaxkDev** [comment]
Better error descriptions are on the todo list though.

**Comment by ghost** [comment]
Oh, I didn't check enough....
Thanks.

**Pull request closed without merging**
